vim.api.nvim_set_keymap('n', '<leader>gs', ":Git <CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>gl', ":Git log <CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>gb', ":Git blame <CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>gp', ":Git push <CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>gdl', ":diffget //2 <CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>gdr', ":diffget //2 <CR>", { noremap = true, silent = true })
